* stack
** mirar API de stripe
** modelo de dados
*** user
    tendeiras ou clientes
**** delivery-address
     nom nos preocupar com billing address até alguém nos pedir fatura.
***** nome
***** lugar/rua
***** número, piso etc.
***** código postal
***** província/regiom/etc.
***** estado
**** payment-method
     ver o que requer stripe
     permitir tamém paypal? ver fees.
*** category
    e.g. camisolas
*** product
    e.g. camisola ramalho.  hai-na em diferentes cores e tamanhos. quando
    procuramos cousas que comprar, a página mínima é esta.  depois pode haver
    diferentes selectores para tamanho, cor, etc.
*** merc
    e.g. camisola dumha cor e tamanho concreta. todos estes elementos som
    intercambiáveis.
*** color
    a cor dumha merc
*** size
    o tamanho dumha merc
** use cases
*** acrescentar categoria?
    só programaticamente, por enquanto.
** implementaçom
*** um servidor em hetzner sobre crux com confluent backend
*** images etc. em S3
** mirar
*** https://github.com/juxt/crux/blob/master/crux-test/test/crux/query_test.clj

* problem statement

  Fazer umha loja online para a Semente.  Venderám-se camisolas, livros,
  crachás, brinquedos, etc.

  As clientes devem poder descobrir facilmente o que hai para vender, bem por
  navegaçom por categorias, bem por procura por keywords. Podem acrescentar
  produtos ao seu carro da compra, podem retirá-los, podem revisar o carro da
  compra, e quando estiverem satisfeitas podem comprar. Para isso tenhem que
  entrar os dados de pagamento em Stripe e os dados de envio. O site calcula
  gastos de envio segundo peso e tamanho da mercadoria e lugar do envio (ver
  tarifas de correios). Tamém tenhem que dar algum dado de contato (email,
  telefone?) para trackeado do envio.

  **Mirar leis de proteçom de dados.**

  Damos-lhe à utente a opçom de salvar os seus dados de pagamento e envio
  abrindo umha conta. Pode ter mais de um endereço de envio e mais do que um
  cartom.

  As gestoras da tenda recebem notificaçom em tempo real (horas configuráveis
  pola gestora, default 9-5) dos pedidos e podem marcá-los como enviados.
  Quando isto acontecer, o cliente pode receber umha notificaçom. Numha
  primeira versom, o flow acaba aqui e o seguimento da entrega é, no seu caso,
  manual.
